modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
displayTest = "IGNORE_ALL_VERSION"

[[mixins]]
config = "atmossway.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.213,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "sway"
type = "required"
versionRange = "[2.4.3,2.5)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "projectatmosphere"
type = "required"
versionRange = "[0.9.1.2,0.10)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "simpleclouds"
type = "required"
versionRange = "[0.7.3,0.8)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "particlerain"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "CLIENT"
reason = "Wind adapter supports Particle Rain 4.0.0-beta.6 and newer; older versions remain unaffected."
